---
title: "teaching"
author: "Chip Brock"
---

# teaching

## ["quarks, spacetime, and the big bang,"](#)

**isp220: MSU**

Particle Physics is a subject of interest to many people, in part because of coverage in the media, but also because of the esoteric nature of quarks, relativity, quantum mechanics, and the connections with cosmology. In this course I present an overview of both fields for general education students who, incidentally, pay for our work through their taxes. The emphasis is on story-telling and elementary mathematics as a language to assist the narrative of history and biography.

### "navigating the universe,"

 **isp213H: MSU**

The Honors College at MSU requested a general educaiton course in 1999. At the time I was chair of the department and assigned the course to myself...and then stepped down as chair. The course is an intellectual history of physics and art, with an emphasis on how we represent our world and how our approaches to representation have evolved over millennia. The course is a writing-intensive experience for students and was well-received for the 8 years that I taught it. I plan to return to it, alternating with isp220, above.

## service and disciplinary courses

My regular curricular teaching has been all over the map, from undergraduate service courses through graduate courses. These include recently: [group theory, relativistic quantum mechanics, relativistic quantum field theory, modern physics, undergraduate laboratory:](#) [PHY911, 852, 853, 215, 252](#)

- **teaching experiences**
  
  I have taught all over the curriculum at Michigan State University since 1982. This includes many semesters in the large lectures for physics with and without calculus. I have also taught many semesters in the graduate curriculum, mostly Particle Physics, Relativistic Quantum Mechanics, Relativisitic Quantum Fielt Theory, and Group Theory. I have also taught Modern Physics in the undergraduate curriculum.
  
- My recent emphasis is in the general education curriculum - at Michigan State, called "Integrative Studies."

  

  ### teaching awards

MSU Teacher Scholar Award, 1985

MSU Distinguished Faculty Award, 2004

Best Graduate Instructor (voted on by graduate students), 1993

Osgood Award for Undergraduate Teaching, 2005