---
title: "research"
author: "Chip Brock"
---

# research

## ATLAS experiment CERN

I have been a member of the ATLAS collaboration since the mid-1990s. I convened the first "Single Top Quark" group and subsequently helped to form the ATLAS Great Lakes Tier 2 computing center with the University of Michigan. This "long baseline" computing center operates seamlessly between our two campuses serving the US ATLAS community along with 4 other Tier 2 centers. In the spring of 2014 we commissioned a $2M electronics project designed and built at MSU as an upgrade to the L1 calorimeter trigger. The boards take advantage of newer FPGA technologies and process data from the detector at 4x the Run 1 rate. They worked flawlessly through Run 2 of the LHC. I'm now working with a colleague to ramp up a "factory" in our labs to construct 20,000 small muon drift chamber tubes for the phase 3 upgrade of ATLAS.

## D0 experiment fermi national accelerator laboratory

I was a charter member of the D0 collaboration which came into existence in 1983. During that time I've had 4 PhD students and convened and then co-convened the first W Mass group. I also was the co-convener of the Database, Datahandling, Datagrid group and chaired the Computing Policy Committee for many years. During our D0 years our group has built and upgraded the L1 Calorimeter trigger, the trigger framework and the 6 sided large scintillator "cap" around the whole detector.

## phenomenology

My PhD degree was shared between the experimental and theoretical groups at Carnegie-Mellon University. My phenomenology work was in the production of heavy flavor in neutrino scattering as well as the production of strange particles in neutrino scattering. My first publication was a single-author *Physical Review Letter*, a feat I've not since replicated. I've subsequently published in the resummation of gluon emission in Drell-Yan production of muons and the NLO corrections to single top quark production in colliders. My training has allowed me to teach advanced particle physics, relativistic quantum mechanics, and relativistic quantum field theory, and to bring these subjects to the general education program.

### research emphases
I have worked in electroweak and QCD physics in both deep ineleastic neutrino scattering experiments and large proton collider experiments.

## publications
  
I am the author or co-author of more than 1000 publications in experimental and theoretical particle physics since 1975.

You can find my publications in ADSABS as Brock, Raymond
## research recognition
- MSU Teacher Scholar Award, 1985
- MSU Distinguished Faculty Award, 2005
- MSU University Distinguished Faculty Award, 2011
- Fellow, American Physical Society, 1999