---
title: "me in 2 seconds"
draft: false
---

I’m a "University Distinguished Professor" in the Physics and Astronomy Department at MSU, and on the MSU faculty since 1982. These days, I also serve as an Adjunct Professor of Physics at Arizona State University.

My bachelor’s degree is in Electrical Engineering from Iowa State University, but I switched gears after working in private industry for a short while. I went on to earn an MS in Physics and Philosophy of Science from Northern Illinois University and then completed my Ph.D. at Carnegie Mellon University, focusing on both theoretical and experimental elementary particle physics. I spent a couple of years as a postdoctoral researcher at the Fermi National Accelerator Laboratory and joined the MSU faculty in 1982.

Like many scientists, I owe my inspiration to a great high school science teacher. For me, that was Walter Hauswald at Sycamore, Illinois High School. He let me help with class prep and encouraged me to explore topics like quantum mechanics outside of class. I was lucky to have him for all three years of my high school physical science courses:  I dedicated my Ph.D. thesis to him.

My family is important to me. Janet and I have been married for more than 50 years and immensely enjoy our two grown kids and grandtwins.

>  BTW. All my life I've been "Chip," although my driver's license and passport say "Raymond." Before you ask, nobody claims to know where this started. Please note before being really proud of yourself: "Chip off the old Brock" is not new, it's not funny anymore, and all of you think you were the first to invent it.
