---
title: "professional"
draft: false
---

I’ve had the chance to take on a variety of service roles in my field, including with the American Physical Society, as well as serving as a reviewer and advisor for organizations like the Department of Energy, the National Science Foundation, the State of Michigan, and several physics departments.

# chair, department of physics and astronomy, Michigan State University

 I served as Chair of the Department of Physics and Astronomy from 1992 to 2000. During that time, we accomplished some exciting projects, including building the Biological and Physical Sciences Building on the MSU campus, helping construct the SOAR telescope in Chile, and bringing the Abrams Planetarium into our department.

# american physical society, division of particles and fields,

I had the honor of serving as Chair of the Division of Particles and Fields (DPF) of the American Physical Society, my professional society for elementary particle physics. It was a four-year commitment, including roles as vice-chair, chair-elect, chair, and past chair. My year as chair was in 2010, and my goal was to solve a major transparency and "buy-in" problem in our decadal, national scientific planning effort. Our "Snowmass" process now directly connects community input to governmental advice.

# US ATLAS IB Chair

From 2014 to 2015, I was the elected Chair of the US ATLAS Institutional Board, which represents the 700 physicists from 50 universities and national laboratories in the US who are part of the ATLAS Collaboration at CERN’s Large Hadron Collider.

# co-chair of the Energy Frontier Subgroup of Snowmass2013

About once a decade, the US particle physics community undertakes a comprehensive study to chart the future of the field. For the 2013---inaugural--- Snowmass Study, I must have missed a meeting, since I found myself co-chairing the "Energy Frontier Subgroup" with Michael Peskin. The field just undertook the second in this now permanent process. 


## professional service roles

### elected positions

  1988--1990; member, Fermilab Users Executive Committee

  1989--1990; Chairman, Fermilab Users Executive Committee

  1998--2000; member, Fermilab Users Executive Committee

  2008--2011; Vice Chair, Chair-Elect, Chair, and Past-Chair, Division of Particles and Fields, American Physical Society.

  2012--2013; Deputy Chair, US ATLAS Institutional Board.

  2014--2015; Chair, US ATLAS Institutional Board.

### appointed positions

  1980--1981; Co--leader (with Leon Lederman) of Arms Control and Disarmament Seminar Series

  1983; member, Fermilab Computer Coordinating Committee

  1988--1989; Physicist on an independent panel appointed by the Governor of Michigan to study the radiological and toxilogical effects of the SSC in Michigan.

  1991; member, Search Committee for the Director of Fermilab (following the retirement of Leon Lederman)

  1991--1995; member, Fermilab Program Advisory Committee

  1991; member, first Fermilab Neutrino Oscillation Panel ad hoc advisory panel to FNAL Director)

  1994; Chairman, second Fermilab Neutrino Oscillation Panel ad hoc advisory panel to FNAL Director)

  1991--1994; member, Los Alamos Meson Physics Facility Physics Advisory Committee

  1992--1995; Special Assistant to the Fermilab Director

  1994--1995; Committee on Long Term Planning, Division of Particles and Fields, American Physical Society.

  1997; Member of the Department of Energy Site visit team to the Stanford Linear Accelerator Laboratory.

  1997--1998; Nominating Committee for the APS Division of Particles and Fields Panofsky Prize.

  1998; Committee for Review of Academic Tenure, American Physical Society.

  2001-current; US-European Working Group to organize VLHC activities.

  2002-2005; University Representative to the DOE High Energy Advisory Panel (HEPAP).  
  2003 (March); I led the University Team in the first-ever "Committee of Visitor"' review of the Department of Energy Office of High Energy Physics.

  2004-5; I co-chaired a task force to understand the physicist resources in the U.S. for the remainder of the decade. This involved a survey of every NSF and DOE grant and every experiment HEP experiment in the world.

  2005; Vice-chair, APS DPF Nominating Committee.

  2006; Chair, APS DPF Nominating Committee.

  2007; Member of the HEPAP Subpanel: "University Grants Program Subpanel"

  2010; Ex Officio member of HEPAP

  2010-2013; U.S. at-large representative to "ICFA"' the International Committee on Future Accelerators

  2012-2013; Co-leader of the Energy Frontier Subbgroup of the US Particle Physics community's Study of the Future of Particle Physics, aka "Snowmass2013"
  2011--2015; member, Fermilab Program Advisory Committee

### external department reviews

  Georgia Tech, 2006.  
  Florida State University, 2008.  
  University of Massachusetts, 2010. University of Indiana, 2016.
