---
title: "about QS&BB"
---

This site is called *Quarks, Spacetime, and the Big Bang* (aka QS&BB), which is an umbrella phrase that covers all of my research in  elementary particle physics. It's also the name of a course I created for non-science students at Michigan State University. 

QS&BB is also a continuation of that teaching...a repackaging of my courses from classical and contemporary topics in relativity, quantum mechanics, particle physics, and cosmology. 

Like the courses, I've prepared this for a non-specialist audience (is that you?) and I hope you'll enjoy the stories, and the pedagogy and learn something new with each post. I actually invented two home-grown courses over the last 20 years and they are:

- *Quarks, Spacetime, and the Big Bang* (MSU ISP220), which pretty much gives away its focus in the name.
-  *Navigating the Universe* (MSU ISP213), a chronological history of physics and art, a course designed for MSU honors students.

QS&BB is a collection of blog posts, which I call "stories" and is my new way of teaching.  I'll bring topics from my courses to the public, along with insights from my 50 years of research at Fermilab in Illinois and CERN’s Large Hadron Collider in Geneva, Switzerland.

