---
title: "teaching"
draft: false
---

Since 1982, I’ve had the opportunity to teach across the entire physics curriculum at Michigan State University. This includes many semesters of large introductory physics lectures, both with and without calculus. At the graduate level, I’ve focused on courses like Particle Physics, Relativistic Quantum Mechanics, Relativistic Quantum Field Theory, and Group Theory. I’ve also enjoyed teaching Modern Physics in the undergraduate curriculum.

My most recent teaching has been to non-science students...the inspiration for this site. 

## "quarks, spacetime, and the big bang"

**isp220: MSU**

Particle physics fascinates many people—not just because of its media coverage, but also thanks to the intriguing world of quarks, relativity, quantum mechanics, and their ties to cosmology. In this course, I offer a broad overview of these fields tailored for general education students—students who, by the way, help fund our work through their taxes. The focus is on storytelling, using simple math as a tool to support the narrative of history and the lives of the scientists behind the discoveries.

## "navigating the universe"


**isp213H: MSU**

Back in 1999, when the MSU Honors College requested a general education course, I was chair of the department and assigned the task to myself—--and stepped down as chair. The result was a unique course exploring the intellectual history of physics and art, focusing on how we represent the world and how those methods have evolved over millennia. It’s a writing-intensive course that students appreciated during the eight years I taught it.

## disciplinary and service courses

Over the years, my teaching has covered just about everything, from introductory service courses for undergraduates to advanced graduate-level classes. Some recent offerings include:

- Undergraduate Service Courses: Modern Physics, undergraduate labs (PHY 215, PHY 252)

- Graduate Courses: Group Theory, Relativistic Quantum Mechanics, Relativistic Quantum Field Theory, and laboratory courses (PHY 911, PHY 852, PHY 853)



## teaching awards

- MSU Teacher Scholar Award, 1985

- MSU Distinguished Faculty Award, 2004

- Best Graduate Instructor (voted on by graduate students), 1993

- Osgood Award for Undergraduate Teaching, 2005
