---
title: "Theories, Laws, and Truth, oh, my."
title-block-banner: A9A9A9
format: html
draft: false
---

::: {.callout-warning icon="false"}
## ℹ️ README:

<br>"It's only a theory" is a phrase wrong enough to make a grown physicist cry. Theories, laws, facts, proof, truth are all related verses in a compliated song and while we scientists know what we mean...it's confusing. Scientists converse in everyday terms. Like normal people. But while we use normal words in real life, some of them are different in scientific life.

As for the crying? Years ago I was triggered by a long argument in the state of Florida.
:::

Around 2008 the Florida State Board of Education was grappling with their "F" grade in a national review of science education. And, predictably instructions to teachers on how to teach evolution was a major issue. A few states insisted on teaching creationism, or the cloak-and-dagger idea of "Intelligent Design," along side of, or in place of actual science.

So after many, many hearings, reports, testimony from Nobel laureats, and very public disputes, The fuss was resolved by mandating that whenever evolution was mentioned, it was to be referred to as the **Theory** of Evolution. By contrast, whenever Newton’s rule regarding gravity was used, it was to be called Newton’s **Law** of Gravitation. Law, good. Theory? Notsomuch. Remembering this story is why I have on my unhappy face right now.\[\^law\]

> 😐 That triggered me and I never taught introductory physics the same after that.

So I have rules (for myself) and in physics classes that I teach that can be summed up as:

## There are no scientific Laws.

The obvious implication of the Florida stalemate is that somehow a theory is less than a law, less believable, less trustworthy, less true, less factually correct. This is demoralizing for us physicists since it can lead to misunderstanding about what science can and cannot do. After thinking about this for many years I have reached a set of conclusions about the Nature of Science (NOS)[^1]

[^1]: The Nature of Science is a term of art in some parts of science education research. Everyone has a slightly different take on the "NOS" and I have mine.

Just to be clear...it is after all my blog 😎 ... I'll not use the word "Law" when I describe scientific ideas.

> **Wait.** What about Newton’s Laws of motion? <br><br> **Glad you asked.** I will talk about historical scientific ideas which got labeled as "Law" but I'll use "law." So: Newton's Second <u>law</u>. Just to make the point, that law is not always correct since it was superceded by Einstein's Theory of Special Relativity. Some "Law"! See that modern use: It's universally the *Theory of Relativity*, not Law of Relativity,

There are other words and phrases that deserve a scientific explanation and here are seven of them, followed by a snapshot of what I have in mind for each. Follow the links for more discussion. Please!

1.  <a href="./NOS/20250514_0100-laws/0100-laws.html" target="_blank">There are no Scientific Laws.</a>
2.  <a href="./NOS/20250514_0200-knowledge/0200-knowledge.html" target="_blank">Scientific knowledge is a unique and reliable kind of knowledge.</a>
3.  <a href="./NOS/20250514_0300-truth/0300-truth.html" target="_blank">Facts change and there is no scientific Truth.</a>
4.  <a href="./NOS/20250514_0400-proof/0400-proof.html" target="_blank">Theories cannot be proven.</a>
5.  <a href="./NOS/20250514_0500-models/0500-models.html" target="_blank">We don't test a theories. We test models.</a>
6.  <a href="./NOS/20250514_0600-reality/0600-reality.html" target="_blank">There is a reality “out there” and our understanding of it continuously improves.</a>
7.  Science is what scientists do.

Squirming yet? Each of the above is a separate post tagged "NOS" so you can find them.

## About laws.

Science is actually contingent by purpose and practice. That is, no scientific statement or set of rules are permanent but always subject to overrule. Hence, no Scientific Laws.

## About knowledge.

We all "know" things in everyday life. I know where I left my keys. That is, my personal belief is that I left them...there. If I go there and don't find my keys then I was wrong, or someone moved my keys. While frustrated, I recognize that I can be wrong about my personal knowledge and I - and I'll be you - have personal strategies to try to figure out where they might be. My strategies are mine. Your's are yours and we don't have to agree about them. A standard way of key-finding need not be a requirement of driving a car.

But scientific knowledge is a little different. First of all, the need for scientists to agree on facts and theories is pretty important. I wouldn't tell you that your way of finding your lost keys is the wrong way, but scientists disagree all the time about whether a path to a conclusion is properly scientific. There is a community acceptable kind of scientific knowledge.

## About theories.

As my Florida story suggests, just what a theory is can be complicated. It's not a "I woke up this morning and had a hunch" kind of thing and it's certainly not an indisputable kind of thing. Theories are somewhere...in the middle.

But theories are also a pubic thing. Scientists need to agree on what a theory is and when an idea has become a theory.

## About facts.

Perhaps by now you know that I'm not a fan of proving anything in science! If I prove a mathematical derivation, it's permanent. Within the rules of mathematics, it cannot be wrong and will be...forever. But I've already been adamant about the lack of "Laws" in science so a proof is obviously not my favorite idea.

That's a principled stand but there's a more practical side that argues against proof. What about a fact? It seems reasonable to imagine that I can make a measurement and establish a fact, even *prove* a fact. A fact can be an existence-thing and it can be a number.

Let me take the second first. Here's a fact: the mass of an electron is $9.109 \times 10^{31}$ kg. I measure that and so will you. It's in books. It's in Wikipedia!

But this will sound silly, but it's maybe one of the most important and most misunderstood things about a scientific fact. If you go an measure the mass of an electron, you might get $9.1093837139 \times 10^{31}$ kg. Those aren't the same number. You might correctly point out that they're close and that the second one is maybe more precise and you'd be right. But what then is the proof of the fact that the electron has a *particular* mass? My fact is then not your fact and we can't prove personal facts and still be scientific.

But there's more. If I were to measure the mass of the electron and report it as "$9.1093837139 \times 10^{31}$" I'd lose my physicist union card. All...every single one...measurement of a physical "fact" is not just a number. It's a number plus a declaration of how well I know that number...the "uncertainty." Thankfully now when political polls are announced, the "margin of error" is reported. So if one candidate's poll number is 49% and the other is 51% with a margin of error of 4%...they are tied. Nobody can be reported to be ahead.

The same thing is true in a scientific "fact" but besides the uncertainty inherent to the number of measurements (statistical uncertainty), there are uncertainties inherent to the measurement device used. If I have a ruler marked off in only whole inches, and I measure something to be 2.5 inches long, then there's an inherent uncertainty in that measurement that's a significant fraction of an inch.

So. Facts about the natural world cannot be proven in the same sense that a mathematical proof can be proven. So when being precise in our language, scientists do not speak of having proven a fact.

9.1093837139(28)×10^−31^ [kg](https://en.wikipedia.org/wiki/Kilogram "Kilogram")^\[1\]^

## About theories: tests

::: {.callout-tip icon="false"}
🔐 Science by yourself and only in your head is not professional science. That is, science is public and how we communicate is through scientific statements. So really when one is evaluating the believability of a scientific idea...what you're really evaluating is a set of statements about that idea. In everyday life, I might toss off a thought casually, without preparation or much analysis. You know, like in a normal conversation. But a scientific statement isn't like that. It's considered, it's carefully put together, it's thoughtful and meaningful. A scientific statement can be a sentence, or a whole book. The point is that a scientific statement has structure and is composed according to professional expectations.
:::

## It is not possible to test a theory. We test models.

I’ve discarded Laws and truth and proof and so it’s time to confront the idea of a theory and how we can trust one or not. “What is a theory,” is a valid question.

### Planes, Trains, and Automobiles: Models

When I was a kid, I was consumed by models of cars— “hot rods” of the 1960s. And airplanes. And HO train sets. In short, life-like replicas of transportation tools were my passion when I wasn’t playing or watching baseball.

A plastic model stands for—represents—a real thing in the world, not perfectly, but well enough to complete a mission. In my case, that mission was a 13 year old boy imagining the car that he’d work on and own some day. If my plastic 1967 Chevy with baby moon wheels, GM 350 cubes with aluminum heads, Edelbrock intake manifold, Holley 4bbl, HPC Coated Headers w/Dual Exhaust, painted baby blue was made more and more precise, it would eventually become...a real car.

chevybox.png intage Revell model ’57 Chevy. In the box.

I’ve been careful in what I wrote above to do two things. First, I referred to scientific **statements** and **models** of nature. Gone are the days when a physicist can construct a mathematical description of say a block of wood sliding down a plane of wood and proudly proclaim that what’s written in symbols on paper is a 1:1 faithful reproduction of what happens in the laboratory.

Now we operate from a more hazy, removed vantage point. As we get into electric and magnetic fields, relativity, and quantum mechanics the correspondence between a mathematical description and what nature is supposed to be like will become necessarily more indirect and abstract.

I now tend to think of a theory as a broad framework within which there are many ways to address nature from within the framework. But what we don’t do is test the theory, rather we build mathematical models that use the rules (from within the framework) of a theory to address a particular, well-defined piece of nature with predictions. Then experiments are done to test the model, not the theory.

Let’s pick on Special Relativity again. I can tell you the Theory of Relativity in these three lines:

1.  The rules of physics are the same in all inertial frames of reference.
2.  The speed of light is the same in all inertial frames of reference.
3.  The interval between two spacetime events is Minkowskian.

The first two statements are called the Postulates of Relativity and the last statement is a consequence of the mathematization of the theory in geometry.

This is the Theory of Relativity…the framework within which any scientific statement must fit. You don’t need to understand what these sentences mean, but you can surely see that they don’t contain a single mathematic equation. That’s where the models come in.

In my way of thinking, a mathematical model of nature is a little machine that you a result at the end when you add some information at the beginning. The result can be, and usually is, the prediction of what an experiment would find. That result can also be another equation, distilled from input equations.

We will use the Theory of Relativity above quite a bit, but our confrontation with nature will be through models that are built within the framework of the Theory of Relativity.

An important aspect of a model is that it must respect a possible measurement’s capabilities. A model is not meant to be a 1:1 representation of nature, just like the model car is not a real car. It’s a limited representation that can be tested. Here’s what I mean.

I can create a model for how fast a block will move across a table if it’s pushed with a given force. If that’s all I want to know, that’s a pretty easy thing to predict. But notice that it’s not the whole story of what goes on. The table and the block heat up and so energy is lost to the warming air. There are billions of little, complex atomic bonds between the under-surface of the block and the table-top. There’s a lot of physics involved in describing this event and how much detail I include in the model depends on a) what I want to know from my measurement and b) how well I need to know it. My model could include all of those thermodynamic and atomic effects but I wouldn’t include them if I can’t measure the speed very precisely.

Physicists learn to stick to the Goldilocks Rule of Modeling. A model can’t be too crude and a model can’t be too precise…a model needs to be Just Right.

To summarize:

-   accept a theory and its rules; build mathematical models within the theory to represent nature (but not in a 1:1 sense);
-   make predictions from those models and test them in experiments;
-   accept or reject the model based on the results of the experiments.

That’s the game that I’ve played for four decades in which I’ve never left the theory of quantum mechanics, the theory of special relativity, nor the theory of general relativity...but I’ve tested lots of models.

#### Statements

It’s a detail, but an important one. We cannot test nature directly. We can only assess the truth or falsity only of statements. This reflects a remoteness of a scientist relative to nature itself. So a prediction and a test of that prediction is really testing statements and not theories and not nature. I confess this is hard to appreciate and I can probably argue even with myself about it.

painting.png *In some ways, what an artist does when she paints a landscape is make a model of it. Representation theory is a serious part of "Semiotics" which is a sophisticated discipline in philosophy, linguistics, and aesthetics.*

### Memory Medicine: Confirmation and Disconfirmation

In my car I just heard an advertisement for a supplement that would make me remember things better. (I don’t remember its name...see what I did there?) It apparently has been “proven” to be effective. Well, by now you know my problems with that word, but what is it that scientists can actually say about a model and indirectly, the theory framework within which it functions?

The black squirrel issue makes it clear that proving, beyond a shadow of a doubt, that an inductive model is true is risky and historically unproductive.

-   The word that we use when evidence supports a model’s prediction is "*confirm*"...the model’s prediction is *confirmed*, definately not “proved.”
-   The word we use when a model’s prediction is contradicted is "disconfirmed.”
-   The burden of any model is that it must be "falsifiable" or in principle be disconfirmable.

A couple of notes. “Confirm” is weaker than prove, leaving us the necessary freedom to allow that evidence can change our models and even theories. Those theories that I keep saying we trust? They have been confirmed many, many times. (It’s fair to think that maybe a Law is just a really, well-confirmed theory. But I’m fighting that older picture of Newtonian-like Laws.)

That last bullet is important and has a special place in the Philosophy of Science—and is the center of a couple of serious arguments in my fields of physics right now.

<aside class="myaside">

You might have heard some of this in the news and the falsifiability test of a theory (the word used then) is attributed to the philosopher, **Karl Popper**. He thought this was a worthy goal of science because showing something to be wrong is actually a deductive process, the inverse of showing that something agrees.

</aside>

To a Popperian (my pejorative word) a single instance of disconfirmation should eliminate a model from study (they would say "theory"). A single black squirrel? That’s nice sounding, but not how science actually works and is philosophically troublesome (ask Mr Google about the Duhem–Quine thesis)–that black squirrel could have just been in a dust-bin.

<p class="pullquote">

The requirement of falsifiability as a standard required of science has pretty much stuck with us.

</p>

Can you see how this in-principle falsifiability requirement actually feeds my original assertion above about how to tell if a statement is scientific or not? The latter is just a simpler version of the former.

The bottom line here is this:

<p class="pullquote">

The burden on science is not to prove things about nature, but to confirm or disconfirm statements about nature.

</p>

In QS&BB, we’ll watch revolutions in science that create large frameworks in which models are tested, rejected, and accepted. These frameworks I will call *theories* and I can list them for you:

1.  Newton’s laws of motion (remember?)
2.  Newton’s law of Gravitation
3.  Maxwell’s Theory of Electromagnetism
4.  Quantum Mechanics
5.  Special Relativity Theory
6.  The General Theory of Relativity

In my picture, there are not many theories in physics.

Other topics like the big bang? quarks? nuclear physics? the standard model of particle physics? These are all models within the currently acceptable theories (frameworks) of 4, 5, and 6 above. Numbers 1 and 2? They’ve been replaced!

### Laziness: Belief

One more word that both has no place in science but is one of those words we use all the time: **Belief.** We all talk about what we believe (and don’t), and scientists will sometimes colloquially do that in a scientific context, but that’s sloppy. When I say “I believe in X,” what I really mean is that that job that word does is act as a shorthand for the sentence: “X is highly confirmed by experiments and X is likely to survive foreseeable experimental tests if asked.” If I’m an expert in the field of X, then I have the obligation to describe those experimental tests. If I’m not an expert in X and I want to echo an expert’s "belief," I should expect that expert could also enumerate its experimental successes in detail on my behalf. (That’s a little tricky.)

There are dos and don’ts here for scientists (and students of science). When it comes to belief in a scientific statement, I can’t do three things:

1.  I can’t say that I believe in X because I want to,
2.  I can’t say that I believe in X because my gut or a “feeling” suggests that I should, and
3.  I can’t say that I believe in X because just because a non-expert or an authoritative text tells me to. Likewise, I can’t say that I *don’t* believe in X for any of those same three reasons.

## There is a reality “out there” and our understanding of it continuously improves.

For more than a decade, there has been a famous war between philosophers and physicists with prominent physicists claiming that little or none of what philosophers of science have said has had any effect on science. The Nobel physicist from the University of Texas, Stephen Weinberg is both a prolific scientist, but also a writer of non-specialist books, the most famous being *The First Three Minutes*. One of his later books for the public is *Dreams of a Final Theory* and his last chapter is called *Against Philosophy* where he notes, “I know how philosophers feel about attempts by scientists at amateur philosophy. But I do not aim here to play the role of a philosopher, but rather that of a specimen, an unregenerate working scientist who finds no help in professional philosophy. I am not alone in this; I know of no one who has participated actively in the advance of physics in the postwar period whose research has been significantly helped by the work of philosophers.”

One of the more disturbing ways in which philosophy of science has drifted is in the denial of the project of science as learning about the physical world. Rather, science is deemed to be a social activity without the ability

## Science is what scientists do.

## Scientific knowledge is a unique kind of knowledge.

What you'll see is that in a very subtle and surprising way, **science is contingent**. Evidence can lead to the overthrow if previously trusted theories. Facts can lose their permanence, proof is impossible except in mathematics, and models are meant to be tested, revised, and tested again.

Doesn't this go against the common notion that science is the final arbiter of truth? It's complicated and when this contingency meets a unique pandemic and scientists are building the airplane while they're flying it, in public, misunderstanding can be the result.
